package PDFService;


/**
* PDFService/_GestionnairePDFStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Thursday, April 30, 2026 10:06:11 PM UTC
*/

public class _GestionnairePDFStub extends org.omg.CORBA.portable.ObjectImpl implements PDFService.GestionnairePDF
{


  // 1. Obtenir les infos d'un PDF
  public PDFService.InfosPDF getInfos (String nomFichier) throws PDFService.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getInfos", true);
                $out.write_string (nomFichier);
                $in = _invoke ($out);
                PDFService.InfosPDF $result = PDFService.InfosPDFHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFService/PDFException:1.0"))
                    throw PDFService.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getInfos (nomFichier        );
            } finally {
                _releaseReply ($in);
            }
  } // getInfos


  // 2. Fusion de plusieurs PDFs en un seul
  public byte[] fusionner (String nom1, String nom2, String nomResultat) throws PDFService.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("fusionner", true);
                $out.write_string (nom1);
                $out.write_string (nom2);
                $out.write_string (nomResultat);
                $in = _invoke ($out);
                byte $result[] = PDFService.FichierHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFService/PDFException:1.0"))
                    throw PDFService.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return fusionner (nom1, nom2, nomResultat        );
            } finally {
                _releaseReply ($in);
            }
  } // fusionner


  // 3. Découpage : extraire certaines pages d'un PDF
  public byte[] extrairePages (String nomFichier, int pageDebut, int pageFin, String nomResultat) throws PDFService.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("extrairePages", true);
                $out.write_string (nomFichier);
                $out.write_long (pageDebut);
                $out.write_long (pageFin);
                $out.write_string (nomResultat);
                $in = _invoke ($out);
                byte $result[] = PDFService.FichierHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFService/PDFException:1.0"))
                    throw PDFService.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return extrairePages (nomFichier, pageDebut, pageFin, nomResultat        );
            } finally {
                _releaseReply ($in);
            }
  } // extrairePages


  // 4. Suppression de pages
  public byte[] supprimerPages (String nomFichier, int[] pages, String nomResultat) throws PDFService.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("supprimerPages", true);
                $out.write_string (nomFichier);
                PDFService.ListePagesHelper.write ($out, pages);
                $out.write_string (nomResultat);
                $in = _invoke ($out);
                byte $result[] = PDFService.FichierHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFService/PDFException:1.0"))
                    throw PDFService.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return supprimerPages (nomFichier, pages, nomResultat        );
            } finally {
                _releaseReply ($in);
            }
  } // supprimerPages


  // 5. Ajout de texte sur une page
  public byte[] ajouterTexte (String nomFichier, String texte, int page, float x, float y, String nomResultat) throws PDFService.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ajouterTexte", true);
                $out.write_string (nomFichier);
                $out.write_string (texte);
                $out.write_long (page);
                $out.write_float (x);
                $out.write_float (y);
                $out.write_string (nomResultat);
                $in = _invoke ($out);
                byte $result[] = PDFService.FichierHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFService/PDFException:1.0"))
                    throw PDFService.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return ajouterTexte (nomFichier, texte, page, x, y, nomResultat        );
            } finally {
                _releaseReply ($in);
            }
  } // ajouterTexte


  // 6. Conversion PDF vers images (retourne les noms des images générées)
  public String[] convertirEnImages (String nomFichier, int dpi) throws PDFService.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("convertirEnImages", true);
                $out.write_string (nomFichier);
                $out.write_long (dpi);
                $in = _invoke ($out);
                String $result[] = PDFService.ListeTextesHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFService/PDFException:1.0"))
                    throw PDFService.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return convertirEnImages (nomFichier, dpi        );
            } finally {
                _releaseReply ($in);
            }
  } // convertirEnImages


  // 7. Extraction de texte de toutes les pages
  public String[] extraireTexte (String nomFichier) throws PDFService.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("extraireTexte", true);
                $out.write_string (nomFichier);
                $in = _invoke ($out);
                String $result[] = PDFService.ListeTextesHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFService/PDFException:1.0"))
                    throw PDFService.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return extraireTexte (nomFichier        );
            } finally {
                _releaseReply ($in);
            }
  } // extraireTexte


  // 8. Création d'un PDF depuis du texte
  public byte[] creerPDF (String texte, String nomResultat) throws PDFService.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("creerPDF", true);
                $out.write_string (texte);
                $out.write_string (nomResultat);
                $in = _invoke ($out);
                byte $result[] = PDFService.FichierHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFService/PDFException:1.0"))
                    throw PDFService.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return creerPDF (texte, nomResultat        );
            } finally {
                _releaseReply ($in);
            }
  } // creerPDF


  // 9. Upload d'un fichier PDF vers le serveur
  public boolean uploadFichier (String nomFichier, byte[] contenu) throws PDFService.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("uploadFichier", true);
                $out.write_string (nomFichier);
                PDFService.FichierHelper.write ($out, contenu);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFService/PDFException:1.0"))
                    throw PDFService.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return uploadFichier (nomFichier, contenu        );
            } finally {
                _releaseReply ($in);
            }
  } // uploadFichier


  // 10. Download d'un fichier PDF depuis le serveur
  public byte[] downloadFichier (String nomFichier) throws PDFService.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("downloadFichier", true);
                $out.write_string (nomFichier);
                $in = _invoke ($out);
                byte $result[] = PDFService.FichierHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFService/PDFException:1.0"))
                    throw PDFService.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return downloadFichier (nomFichier        );
            } finally {
                _releaseReply ($in);
            }
  } // downloadFichier


  // 11. Lister les fichiers disponibles sur le serveur
  public String[] listerFichiers () throws PDFService.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listerFichiers", true);
                $in = _invoke ($out);
                String $result[] = PDFService.ListeTextesHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFService/PDFException:1.0"))
                    throw PDFService.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listerFichiers (        );
            } finally {
                _releaseReply ($in);
            }
  } // listerFichiers


  // 12. Rotation de pages
  public byte[] rotationPages (String nomFichier, int[] pages, int angle, String nomResultat) throws PDFService.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("rotationPages", true);
                $out.write_string (nomFichier);
                PDFService.ListePagesHelper.write ($out, pages);
                $out.write_long (angle);
                $out.write_string (nomResultat);
                $in = _invoke ($out);
                byte $result[] = PDFService.FichierHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFService/PDFException:1.0"))
                    throw PDFService.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return rotationPages (nomFichier, pages, angle, nomResultat        );
            } finally {
                _releaseReply ($in);
            }
  } // rotationPages


  // 13. Protection par mot de passe
  public byte[] protegerPDF (String nomFichier, String motDePasse, String nomResultat) throws PDFService.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("protegerPDF", true);
                $out.write_string (nomFichier);
                $out.write_string (motDePasse);
                $out.write_string (nomResultat);
                $in = _invoke ($out);
                byte $result[] = PDFService.FichierHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFService/PDFException:1.0"))
                    throw PDFService.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return protegerPDF (nomFichier, motDePasse, nomResultat        );
            } finally {
                _releaseReply ($in);
            }
  } // protegerPDF


  // 14. Compression PDF
  public byte[] compresserPDF (String nomFichier, String nomResultat) throws PDFService.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("compresserPDF", true);
                $out.write_string (nomFichier);
                $out.write_string (nomResultat);
                $in = _invoke ($out);
                byte $result[] = PDFService.FichierHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFService/PDFException:1.0"))
                    throw PDFService.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return compresserPDF (nomFichier, nomResultat        );
            } finally {
                _releaseReply ($in);
            }
  } // compresserPDF


  // 15. Numérotation des pages
  public byte[] numeroterPages (String nomFichier, String nomResultat) throws PDFService.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("numeroterPages", true);
                $out.write_string (nomFichier);
                $out.write_string (nomResultat);
                $in = _invoke ($out);
                byte $result[] = PDFService.FichierHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFService/PDFException:1.0"))
                    throw PDFService.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return numeroterPages (nomFichier, nomResultat        );
            } finally {
                _releaseReply ($in);
            }
  } // numeroterPages


  // 16. Aperçu : convertir une page en image base64
  public String apercuPage (String nomFichier, int page) throws PDFService.PDFException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("apercuPage", true);
                $out.write_string (nomFichier);
                $out.write_long (page);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:PDFService/PDFException:1.0"))
                    throw PDFService.PDFExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return apercuPage (nomFichier, page        );
            } finally {
                _releaseReply ($in);
            }
  } // apercuPage

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PDFService/GestionnairePDF:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "PDFService._GestionnairePDFStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GestionnairePDFStub
