package PDFService;


/**
* PDFService/FichierHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Thursday, April 30, 2026 10:06:11 PM UTC
*/


// Séquence d'octets pour transférer les fichiers PDF en binaire
public final class FichierHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public FichierHolder ()
  {
  }

  public FichierHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFService.FichierHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFService.FichierHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFService.FichierHelper.type ();
  }

}
