package PDFService;


/**
* PDFService/GestionnairePDFOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Thursday, April 30, 2026 10:06:11 PM UTC
*/

public interface GestionnairePDFOperations 
{

  // 1. Obtenir les infos d'un PDF
  PDFService.InfosPDF getInfos (String nomFichier) throws PDFService.PDFException;

  // 2. Fusion de plusieurs PDFs en un seul
  byte[] fusionner (String nom1, String nom2, String nomResultat) throws PDFService.PDFException;

  // 3. Découpage : extraire certaines pages d'un PDF
  byte[] extrairePages (String nomFichier, int pageDebut, int pageFin, String nomResultat) throws PDFService.PDFException;

  // 4. Suppression de pages
  byte[] supprimerPages (String nomFichier, int[] pages, String nomResultat) throws PDFService.PDFException;

  // 5. Ajout de texte sur une page
  byte[] ajouterTexte (String nomFichier, String texte, int page, float x, float y, String nomResultat) throws PDFService.PDFException;

  // 6. Conversion PDF vers images (retourne les noms des images générées)
  String[] convertirEnImages (String nomFichier, int dpi) throws PDFService.PDFException;

  // 7. Extraction de texte de toutes les pages
  String[] extraireTexte (String nomFichier) throws PDFService.PDFException;

  // 8. Création d'un PDF depuis du texte
  byte[] creerPDF (String texte, String nomResultat) throws PDFService.PDFException;

  // 9. Upload d'un fichier PDF vers le serveur
  boolean uploadFichier (String nomFichier, byte[] contenu) throws PDFService.PDFException;

  // 10. Download d'un fichier PDF depuis le serveur
  byte[] downloadFichier (String nomFichier) throws PDFService.PDFException;

  // 11. Lister les fichiers disponibles sur le serveur
  String[] listerFichiers () throws PDFService.PDFException;

  // 12. Rotation de pages
  byte[] rotationPages (String nomFichier, int[] pages, int angle, String nomResultat) throws PDFService.PDFException;

  // 13. Protection par mot de passe
  byte[] protegerPDF (String nomFichier, String motDePasse, String nomResultat) throws PDFService.PDFException;

  // 14. Compression PDF
  byte[] compresserPDF (String nomFichier, String nomResultat) throws PDFService.PDFException;

  // 15. Numérotation des pages
  byte[] numeroterPages (String nomFichier, String nomResultat) throws PDFService.PDFException;

  // 16. Aperçu : convertir une page en image base64
  String apercuPage (String nomFichier, int page) throws PDFService.PDFException;
} // interface GestionnairePDFOperations
