package PDFService;

/**
* PDFService/GestionnairePDFHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Thursday, April 30, 2026 10:06:11 PM UTC
*/

public final class GestionnairePDFHolder implements org.omg.CORBA.portable.Streamable
{
  public PDFService.GestionnairePDF value = null;

  public GestionnairePDFHolder ()
  {
  }

  public GestionnairePDFHolder (PDFService.GestionnairePDF initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFService.GestionnairePDFHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFService.GestionnairePDFHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFService.GestionnairePDFHelper.type ();
  }

}
