package PDFService;


/**
* PDFService/GestionnairePDFPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Thursday, April 30, 2026 10:06:11 PM UTC
*/

public abstract class GestionnairePDFPOA extends org.omg.PortableServer.Servant
 implements PDFService.GestionnairePDFOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getInfos", new java.lang.Integer (0));
    _methods.put ("fusionner", new java.lang.Integer (1));
    _methods.put ("extrairePages", new java.lang.Integer (2));
    _methods.put ("supprimerPages", new java.lang.Integer (3));
    _methods.put ("ajouterTexte", new java.lang.Integer (4));
    _methods.put ("convertirEnImages", new java.lang.Integer (5));
    _methods.put ("extraireTexte", new java.lang.Integer (6));
    _methods.put ("creerPDF", new java.lang.Integer (7));
    _methods.put ("uploadFichier", new java.lang.Integer (8));
    _methods.put ("downloadFichier", new java.lang.Integer (9));
    _methods.put ("listerFichiers", new java.lang.Integer (10));
    _methods.put ("rotationPages", new java.lang.Integer (11));
    _methods.put ("protegerPDF", new java.lang.Integer (12));
    _methods.put ("compresserPDF", new java.lang.Integer (13));
    _methods.put ("numeroterPages", new java.lang.Integer (14));
    _methods.put ("apercuPage", new java.lang.Integer (15));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // 1. Obtenir les infos d'un PDF
       case 0:  // PDFService/GestionnairePDF/getInfos
       {
         try {
           String nomFichier = in.read_string ();
           PDFService.InfosPDF $result = null;
           $result = this.getInfos (nomFichier);
           out = $rh.createReply();
           PDFService.InfosPDFHelper.write (out, $result);
         } catch (PDFService.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFService.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // 2. Fusion de plusieurs PDFs en un seul
       case 1:  // PDFService/GestionnairePDF/fusionner
       {
         try {
           String nom1 = in.read_string ();
           String nom2 = in.read_string ();
           String nomResultat = in.read_string ();
           byte $result[] = null;
           $result = this.fusionner (nom1, nom2, nomResultat);
           out = $rh.createReply();
           PDFService.FichierHelper.write (out, $result);
         } catch (PDFService.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFService.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // 3. Découpage : extraire certaines pages d'un PDF
       case 2:  // PDFService/GestionnairePDF/extrairePages
       {
         try {
           String nomFichier = in.read_string ();
           int pageDebut = in.read_long ();
           int pageFin = in.read_long ();
           String nomResultat = in.read_string ();
           byte $result[] = null;
           $result = this.extrairePages (nomFichier, pageDebut, pageFin, nomResultat);
           out = $rh.createReply();
           PDFService.FichierHelper.write (out, $result);
         } catch (PDFService.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFService.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // 4. Suppression de pages
       case 3:  // PDFService/GestionnairePDF/supprimerPages
       {
         try {
           String nomFichier = in.read_string ();
           int pages[] = PDFService.ListePagesHelper.read (in);
           String nomResultat = in.read_string ();
           byte $result[] = null;
           $result = this.supprimerPages (nomFichier, pages, nomResultat);
           out = $rh.createReply();
           PDFService.FichierHelper.write (out, $result);
         } catch (PDFService.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFService.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // 5. Ajout de texte sur une page
       case 4:  // PDFService/GestionnairePDF/ajouterTexte
       {
         try {
           String nomFichier = in.read_string ();
           String texte = in.read_string ();
           int page = in.read_long ();
           float x = in.read_float ();
           float y = in.read_float ();
           String nomResultat = in.read_string ();
           byte $result[] = null;
           $result = this.ajouterTexte (nomFichier, texte, page, x, y, nomResultat);
           out = $rh.createReply();
           PDFService.FichierHelper.write (out, $result);
         } catch (PDFService.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFService.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // 6. Conversion PDF vers images (retourne les noms des images générées)
       case 5:  // PDFService/GestionnairePDF/convertirEnImages
       {
         try {
           String nomFichier = in.read_string ();
           int dpi = in.read_long ();
           String $result[] = null;
           $result = this.convertirEnImages (nomFichier, dpi);
           out = $rh.createReply();
           PDFService.ListeTextesHelper.write (out, $result);
         } catch (PDFService.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFService.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // 7. Extraction de texte de toutes les pages
       case 6:  // PDFService/GestionnairePDF/extraireTexte
       {
         try {
           String nomFichier = in.read_string ();
           String $result[] = null;
           $result = this.extraireTexte (nomFichier);
           out = $rh.createReply();
           PDFService.ListeTextesHelper.write (out, $result);
         } catch (PDFService.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFService.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // 8. Création d'un PDF depuis du texte
       case 7:  // PDFService/GestionnairePDF/creerPDF
       {
         try {
           String texte = in.read_string ();
           String nomResultat = in.read_string ();
           byte $result[] = null;
           $result = this.creerPDF (texte, nomResultat);
           out = $rh.createReply();
           PDFService.FichierHelper.write (out, $result);
         } catch (PDFService.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFService.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // 9. Upload d'un fichier PDF vers le serveur
       case 8:  // PDFService/GestionnairePDF/uploadFichier
       {
         try {
           String nomFichier = in.read_string ();
           byte contenu[] = PDFService.FichierHelper.read (in);
           boolean $result = false;
           $result = this.uploadFichier (nomFichier, contenu);
           out = $rh.createReply();
           out.write_boolean ($result);
         } catch (PDFService.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFService.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // 10. Download d'un fichier PDF depuis le serveur
       case 9:  // PDFService/GestionnairePDF/downloadFichier
       {
         try {
           String nomFichier = in.read_string ();
           byte $result[] = null;
           $result = this.downloadFichier (nomFichier);
           out = $rh.createReply();
           PDFService.FichierHelper.write (out, $result);
         } catch (PDFService.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFService.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // 11. Lister les fichiers disponibles sur le serveur
       case 10:  // PDFService/GestionnairePDF/listerFichiers
       {
         try {
           String $result[] = null;
           $result = this.listerFichiers ();
           out = $rh.createReply();
           PDFService.ListeTextesHelper.write (out, $result);
         } catch (PDFService.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFService.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // 12. Rotation de pages
       case 11:  // PDFService/GestionnairePDF/rotationPages
       {
         try {
           String nomFichier = in.read_string ();
           int pages[] = PDFService.ListePagesHelper.read (in);
           int angle = in.read_long ();
           String nomResultat = in.read_string ();
           byte $result[] = null;
           $result = this.rotationPages (nomFichier, pages, angle, nomResultat);
           out = $rh.createReply();
           PDFService.FichierHelper.write (out, $result);
         } catch (PDFService.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFService.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // 13. Protection par mot de passe
       case 12:  // PDFService/GestionnairePDF/protegerPDF
       {
         try {
           String nomFichier = in.read_string ();
           String motDePasse = in.read_string ();
           String nomResultat = in.read_string ();
           byte $result[] = null;
           $result = this.protegerPDF (nomFichier, motDePasse, nomResultat);
           out = $rh.createReply();
           PDFService.FichierHelper.write (out, $result);
         } catch (PDFService.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFService.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // 14. Compression PDF
       case 13:  // PDFService/GestionnairePDF/compresserPDF
       {
         try {
           String nomFichier = in.read_string ();
           String nomResultat = in.read_string ();
           byte $result[] = null;
           $result = this.compresserPDF (nomFichier, nomResultat);
           out = $rh.createReply();
           PDFService.FichierHelper.write (out, $result);
         } catch (PDFService.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFService.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // 15. Numérotation des pages
       case 14:  // PDFService/GestionnairePDF/numeroterPages
       {
         try {
           String nomFichier = in.read_string ();
           String nomResultat = in.read_string ();
           byte $result[] = null;
           $result = this.numeroterPages (nomFichier, nomResultat);
           out = $rh.createReply();
           PDFService.FichierHelper.write (out, $result);
         } catch (PDFService.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFService.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }


  // 16. Aperçu : convertir une page en image base64
       case 15:  // PDFService/GestionnairePDF/apercuPage
       {
         try {
           String nomFichier = in.read_string ();
           int page = in.read_long ();
           String $result = null;
           $result = this.apercuPage (nomFichier, page);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (PDFService.PDFException $ex) {
           out = $rh.createExceptionReply ();
           PDFService.PDFExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PDFService/GestionnairePDF:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GestionnairePDF _this() 
  {
    return GestionnairePDFHelper.narrow(
    super._this_object());
  }

  public GestionnairePDF _this(org.omg.CORBA.ORB orb) 
  {
    return GestionnairePDFHelper.narrow(
    super._this_object(orb));
  }


} // class GestionnairePDFPOA
