package PDFService;


/**
* PDFService/GestionnairePDF.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Thursday, April 30, 2026 10:06:11 PM UTC
*/

public interface GestionnairePDF extends GestionnairePDFOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionnairePDF
