package PDFService;


/**
* PDFService/GestionnairePDFHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Thursday, April 30, 2026 10:06:11 PM UTC
*/

abstract public class GestionnairePDFHelper
{
  private static String  _id = "IDL:PDFService/GestionnairePDF:1.0";

  public static void insert (org.omg.CORBA.Any a, PDFService.GestionnairePDF that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PDFService.GestionnairePDF extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (PDFService.GestionnairePDFHelper.id (), "GestionnairePDF");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PDFService.GestionnairePDF read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GestionnairePDFStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PDFService.GestionnairePDF value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static PDFService.GestionnairePDF narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PDFService.GestionnairePDF)
      return (PDFService.GestionnairePDF)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PDFService._GestionnairePDFStub stub = new PDFService._GestionnairePDFStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static PDFService.GestionnairePDF unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PDFService.GestionnairePDF)
      return (PDFService.GestionnairePDF)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PDFService._GestionnairePDFStub stub = new PDFService._GestionnairePDFStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
