package PDFService;


/**
* PDFService/InfosPDF.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Thursday, April 30, 2026 10:06:11 PM UTC
*/

public final class InfosPDF implements org.omg.CORBA.portable.IDLEntity
{
  public String nomFichier = null;
  public int nombrePages = (int)0;
  public String auteur = null;
  public String titre = null;
  public int tailleFichier = (int)0;

  public InfosPDF ()
  {
  } // ctor

  public InfosPDF (String _nomFichier, int _nombrePages, String _auteur, String _titre, int _tailleFichier)
  {
    nomFichier = _nomFichier;
    nombrePages = _nombrePages;
    auteur = _auteur;
    titre = _titre;
    tailleFichier = _tailleFichier;
  } // ctor

} // class InfosPDF
