package PDFService;

/**
* PDFService/InfosPDFHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Thursday, April 30, 2026 10:06:11 PM UTC
*/

public final class InfosPDFHolder implements org.omg.CORBA.portable.Streamable
{
  public PDFService.InfosPDF value = null;

  public InfosPDFHolder ()
  {
  }

  public InfosPDFHolder (PDFService.InfosPDF initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFService.InfosPDFHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFService.InfosPDFHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFService.InfosPDFHelper.type ();
  }

}
