package PDFService;


/**
* PDFService/ListeTextesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Thursday, April 30, 2026 10:06:11 PM UTC
*/


// Séquence de strings pour les pages de texte
public final class ListeTextesHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public ListeTextesHolder ()
  {
  }

  public ListeTextesHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFService.ListeTextesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFService.ListeTextesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFService.ListeTextesHelper.type ();
  }

}
