package PDFService;


/**
* PDFService/ListePagesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Thursday, April 30, 2026 10:06:11 PM UTC
*/


// Séquence d'entiers pour les numéros de pages
public final class ListePagesHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public ListePagesHolder ()
  {
  }

  public ListePagesHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFService.ListePagesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFService.ListePagesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFService.ListePagesHelper.type ();
  }

}
