package PDFService;


/**
* PDFService/PDFException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Thursday, April 30, 2026 10:06:11 PM UTC
*/

public final class PDFException extends org.omg.CORBA.UserException
{
  public String message = null;

  public PDFException ()
  {
    super(PDFExceptionHelper.id());
  } // ctor

  public PDFException (String _message)
  {
    super(PDFExceptionHelper.id());
    message = _message;
  } // ctor


  public PDFException (String $reason, String _message)
  {
    super(PDFExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class PDFException
