package PDFService;

/**
* PDFService/PDFExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Thursday, April 30, 2026 10:06:11 PM UTC
*/

public final class PDFExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public PDFService.PDFException value = null;

  public PDFExceptionHolder ()
  {
  }

  public PDFExceptionHolder (PDFService.PDFException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFService.PDFExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFService.PDFExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFService.PDFExceptionHelper.type ();
  }

}
